CREATE TABLE [dbo].[Participant] (
    [Id] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    [FirstName] NVARCHAR(100) NOT NULL,
    [LastName] NVARCHAR(100) NOT NULL,
    [Email] NVARCHAR(320) NOT NULL,
    [CompanyName] NVARCHAR(200) NOT NULL,
    [CreatedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    [UpdatedAtUtc] DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [PK_Participant] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [UQ_Participant_Email] UNIQUE ([Email])
);
GO
